// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using schiessmeister_csharp.Domain.Repositories.MySqlRepositories;

#nullable disable

namespace schiessmeister_csharp.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20250321140738_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("schiessmeister_csharp.Domain.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrganizerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Competition");
                });

            modelBuilder.Entity("schiessmeister_csharp.Domain.Models.Organizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Organizers");
                });

            modelBuilder.Entity("schiessmeister_csharp.Domain.Models.Competition", b =>
                {
                    b.HasOne("schiessmeister_csharp.Domain.Models.Organizer", null)
                        .WithMany("Competition")
                        .HasForeignKey("OrganizerId");
                });

            modelBuilder.Entity("schiessmeister_csharp.Domain.Models.Organizer", b =>
                {
                    b.Navigation("Competition");
                });
#pragma warning restore 612, 618
        }
    }
}
